blank_issues_enabled: true
contact_links:
  - name: Steam Workshop
    url: https://steamcommunity.com/sharedfiles/filedetails/?id=3668197831
    about: Official distribution and discussion on Steam Workshop
